"""Fix courses table

Revision ID: 387419b7a152
Revises: 98c56467c042
Create Date: 2025-07-20 15:33:44.022405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387419b7a152'
down_revision = '98c56467c042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
