"""testing

Revision ID: 398997537819
Revises: 
Create Date: 2025-07-20 15:30:50.353765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398997537819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
