"""Add Artwork and ArtworkImage tables

Revision ID: 443ca93a6379
Revises: 08b57f3179b5
Create Date: 2025-09-08 17:31:58.885055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443ca93a6379'
down_revision = '08b57f3179b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artwork_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork_images')
    op.drop_table('artworks')
    # ### end Alembic commands ###
